services:
  backend:
    networks:
      devflow_internal: {}
      devflow_edge:
        aliases:
          - devflow-backend

  frontend:
    networks:
      devflow_edge:
        aliases:
          - devflow-frontend
