const express = require('express');
const controller = require('../controllers/taskController');
const attachmentService = require('../services/attachmentService');
const { requireAuth, requirePermission, requireSuperAdmin } = require('../middleware/authMiddleware');

const router = express.Router();
router.use(requireAuth);
router.get('/trash', requirePermission('tasks.manage'), controller.listTrash);
router.delete('/trash', requireSuperAdmin, controller.emptyTrash);
router.get('/', requirePermission('tasks.view'), controller.listTasks);
router.post('/', requirePermission('tasks.create'), controller.createTask);
router.get('/:id', requirePermission('tasks.view'), controller.detail);
router.delete('/:id', requirePermission('tasks.manage'), controller.deleteTask);
router.post('/:id/restore', requirePermission('tasks.manage'), controller.restoreTask);
router.post('/:id/transition', requirePermission('tasks.operate'), controller.transition);
router.post('/:id/state', requirePermission('tasks.manage'), controller.stateAction);
router.patch('/:id/administration', requirePermission('tasks.manage'), controller.updateAdministration);
router.post('/:id/timer', requirePermission('tasks.operate'), controller.timerAction);
router.put('/:id/submission', requirePermission('tasks.operate'), controller.saveSubmission);
router.post('/:id/tests', requirePermission('tasks.operate'), controller.addTest);
router.patch('/:id/tests/:testId', requirePermission('tasks.operate'), controller.updateTest);
router.delete('/:id/tests/:testId', requirePermission('tasks.operate'), controller.deleteTest);
router.post('/:id/approvals', requirePermission('tasks.operate'), controller.addApproval);
router.post('/:id/github', requirePermission('tasks.operate'), controller.addGithub);
router.patch('/:id/github/:cardId', requirePermission('tasks.operate'), controller.updateGithub);
router.delete('/:id/github/:cardId', requirePermission('tasks.manage'), controller.deleteGithub);
router.post('/:id/comments', requirePermission('tasks.operate'), controller.addComment);
router.post('/:id/attachments', requirePermission('tasks.operate'), attachmentService.upload.single('file'), controller.uploadAttachment);
router.get('/:id/attachments/:attachmentId', requirePermission('tasks.view'), controller.downloadAttachment);
router.delete('/:id/attachments/:attachmentId', requirePermission('tasks.manage'), controller.deleteAttachment);

module.exports = router;
